name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build Test
      run: cmake -S . -B build
    - name: Scan Dependencies
      run: cmake --build build
    - name: Run Tests
      run: cd build && ctest
